# Generated by Django 3.1.7 on 2021-03-23 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.BigIntegerField(default='939349484081954', primary_key=True, serialize=False)),
                ('register_date', models.DateField(auto_now=True)),
                ('previous_ctmer', models.BooleanField(default=False)),
                ('has_sons', models.BooleanField()),
                ('is_married', models.BooleanField()),
                ('is_local', models.BooleanField()),
                ('residence', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SuperMarket',
            fields=[
                ('supermarket_id', models.BigIntegerField(default='612066929378476', primary_key=True, serialize=False)),
                ('supermarket_name', models.CharField(max_length=100)),
                ('register_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.BigIntegerField(default='869889841611220')),
                ('item_id', models.BigIntegerField()),
                ('pay_method', models.IntegerField()),
                ('price', models.FloatField()),
                ('item_cnt', models.SmallIntegerField()),
                ('bill_id', models.BigIntegerField()),
                ('transaction_dt', models.DateField(auto_now=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.customer')),
                ('sp_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.supermarket')),
            ],
        ),
    ]
