# Generated by Django 3.1.7 on 2021-03-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.BigIntegerField(default='473577782669634', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='supermarket_id',
            field=models.BigIntegerField(default='157827240360816', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.BigIntegerField(default='41534757920730'),
        ),
    ]
