# Generated by Django 3.1.7 on 2021-03-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20210323_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.BigIntegerField(default='394835165715265', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='supermarket_id',
            field=models.BigIntegerField(default='138242334484696', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.BigIntegerField(default='195743795046288'),
        ),
    ]
