# Generated by Django 3.1.7 on 2021-03-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20210323_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.BigIntegerField(default='930036682938068', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='supermarket_id',
            field=models.BigIntegerField(default='303288752758488', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.BigIntegerField(default='95525182049812', primary_key=True, serialize=False),
        ),
    ]
