"""empty message

Revision ID: cf7451302d6b
Revises: 
Create Date: 2021-03-16 19:20:48.795636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf7451302d6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_metrics',
    sa.Column('supermarket_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('total_volume', sa.Integer(), nullable=True),
    sa.Column('total_tx', sa.Float(), nullable=True),
    sa.Column('last_tx', sa.DateTime(), nullable=True),
    sa.Column('n_cash_payment', sa.Integer(), nullable=True),
    sa.Column('n_card_payment', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('supermarket_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_metrics')
    # ### end Alembic commands ###
