"""empty message

Revision ID: 363cb2c3f23f
Revises: 8d88252374f9
Create Date: 2021-03-15 20:17:58.254803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363cb2c3f23f'
down_revision = '8d88252374f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_metrics', sa.Column('current_month', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_metrics', 'current_month')
    # ### end Alembic commands ###
