"""empty message

Revision ID: 5132420a7665
Revises: 363cb2c3f23f
Create Date: 2021-03-15 20:20:00.872652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5132420a7665'
down_revision = '363cb2c3f23f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_metrics', sa.Column('current_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_metrics', 'current_year')
    # ### end Alembic commands ###
