"""empty message

Revision ID: 8d88252374f9
Revises: b58f3d999324
Create Date: 2021-03-15 20:07:25.368170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d88252374f9'
down_revision = 'b58f3d999324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_metrics',
    sa.Column('customer_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('total_tx', sa.Integer(), nullable=True),
    sa.Column('last_month_volume', sa.Float(), nullable=True),
    sa.Column('n_cash_payment', sa.Integer(), nullable=True),
    sa.Column('n_card_payment', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_metrics')
    # ### end Alembic commands ###
