version: '3.8'

services:
  backoffice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - python_micro
    volumes:
      - .:/app
    depends_on:
      - database

  database:
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - python_micro
    volumes:
      - ./backoffice/db_data:/var/lib/mysql
    ports:
      - 3306:3306

networks:
  python_micro:
    driver: bridge